name: pyjokes-app-cicd-pipeline
on:
  push:
    branches:
      - "ecr-repo"

jobs:
  # Linting Jobs
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint code
        run: |
          flake8 .
  
  # Test Job
  testing:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest 

  # Build docker image and push to ECR repository
  build-and-push:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
           
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_NAME }}:v0.1.${{ github.run_number }} .
          docker build -t $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_NAME }}:latest .

      - name: Check Image Format
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "$ECR_REGISTRY/${{ vars.ECR_REPOSITORY_NAME }}:v0.1.${{ github.run_number }}"
          echo "$ECR_REGISTRY/${{ vars.ECR_REPOSITORY_NAME }}:latest"

      - name: Push Image to ECR Repository
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_NAME }}:v0.1.${{ github.run_number }}
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY_NAME }}:latest


  # Update Helm Chart from other repository
  Update-Helm-Chart:
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:
      - name: Helm Repository Clone
        uses: actions/checkout@v2
        with:
          repository: EdagPSIT/jokes-app-helm-chart.git
          ref: ecr
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update values.yaml
        uses: rmeneely/update-yaml@v1
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          infile: values.yaml
          varlist: 'image.tag=v0.1.${{ github.run_number }}'

      - name: Commit Changes
        run: |
          git config --global user.name "EdagPSIT"
          git config --global user.email "vhanamaneramesh@gmail.com"
          git add values.yaml
          git commit -m "Update values.yaml for v0.1.${{ github.run_number }}"
      
      - name: Push Changes to Repository
        run: |
          git push origin ecr